name: Deploy to Heroku

on:
  push:
    branches:
      - main

env:
  HEROKU_APP_NAME: "adolfovillalobos-status"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build the application
      run: npm run build

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.13.15
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "${{ env.HEROKU_APP_NAME }}"
        heroku_email: "adolfo.villalobos.vega@gmail.com"
